import { z } from 'zod';
import { createApiOperation } from '../../../../../core';
import { type operations } from '../../../../../generated/apps/validator/src/main/openapi/validator-internal';

/**
 * Submit signed external party topology transactions
 *
 * Submits the topology transactions that were generated by generateExternalPartyTopology along with their signatures.
 *
 * @example
 *   ```typescript
 *   const result = await client.submitExternalPartyTopology({
 *     public_key: 'hex-encoded-ed25519-public-key',
 *     signed_topology_txs: [
 *       {
 *         topology_tx: 'base64-encoded-transaction',
 *         signed_hash: 'hex-encoded-signature'
 *       }
 *     ]
 *   });
 *   ```;
 */
export const SubmitExternalPartyTopology = createApiOperation<
  operations['submitExternalPartyTopology']['requestBody']['content']['application/json'],
  operations['submitExternalPartyTopology']['responses']['200']['content']['application/json']
>({
  paramsSchema: z.object({
    public_key: z.string(),
    signed_topology_txs: z.array(
      z.object({
        topology_tx: z.string(),
        signed_hash: z.string(),
      })
    ),
  }) as z.ZodType<operations['submitExternalPartyTopology']['requestBody']['content']['application/json']>,
  method: 'POST',
  buildUrl: (_params, apiUrl: string) => `${apiUrl}/api/validator/v0/admin/external-party/topology/submit`,
  buildRequestData: (params) => params,
});
