import { z } from 'zod';
import { createApiOperation, createRequestSchema } from '../../../../../core';
import { type operations } from '../../../../../generated/apps/validator/src/main/openapi/validator-internal';

type SubmitExternalPartyTopologyRequest =
  operations['submitExternalPartyTopology']['requestBody']['content']['application/json'];
type SignedTopologyTransaction = SubmitExternalPartyTopologyRequest['signed_topology_txs'][number];

const SignedTopologyTransactionSchema = createRequestSchema<SignedTopologyTransaction>()({
  topology_tx: z.string(),
  signed_hash: z.string(),
});

/** Runtime schema kept in exact key/type parity with the generated topology-submission request. */
export const SubmitExternalPartyTopologyParamsSchema = createRequestSchema<SubmitExternalPartyTopologyRequest>()({
  public_key: z.string(),
  signed_topology_txs: z.array(SignedTopologyTransactionSchema),
});

/**
 * Submit signed external party topology transactions
 *
 * Submits the topology transactions that were generated by generateExternalPartyTopology along with their signatures.
 *
 * @example
 *   ```typescript
 *   const result = await client.submitExternalPartyTopology({
 *     public_key: 'hex-encoded-ed25519-public-key',
 *     signed_topology_txs: [
 *       {
 *         topology_tx: 'base64-encoded-transaction',
 *         signed_hash: 'hex-encoded-signature'
 *       }
 *     ]
 *   });
 *   ```;
 */
export const SubmitExternalPartyTopology = createApiOperation<
  SubmitExternalPartyTopologyRequest,
  operations['submitExternalPartyTopology']['responses']['200']['content']['application/json']
>({
  paramsSchema: SubmitExternalPartyTopologyParamsSchema,
  method: 'POST',
  buildUrl: (_params, apiUrl: string) => `${apiUrl}/api/validator/v0/admin/external-party/topology/submit`,
  buildRequestData: (params) => params,
});
