/**
 * Complete topic registry — all 58 founder articles.
 *
 * Each entry mirrors the frontmatter of the corresponding Markdown file in
 * `founders/`.  When the doc-agent runs, it iterates these topics, gathers
 * source context, and feeds it to the LLM.
 *
 * To add a new article: create the file in `founders/`, then add an entry here.
 */
import type { ArticleTopic } from "./types.js";

/* ─── Section 1: Getting Started & Overview ────────────────────────── */

const S1_GETTING_STARTED: ArticleTopic[] = [
  {
    filePath: "founders/1.1-how-does-fairmint-work.md",
    title: "How Does Fairmint Work?",
    section: "1. Getting Started & Overview",
    number: "1.1",
    audience: "Shared",
    gate: "None",
    collection: "Getting Started",
    searchTerms: ["how fairmint works", "platform overview", "equity management"],
  },
  {
    filePath: "founders/1.2-what-is-fairmint-one.md",
    title: "What is Fairmint One?",
    section: "1. Getting Started & Overview",
    number: "1.2",
    audience: "Shared",
    gate: "None",
    collection: "Getting Started",
    searchTerms: ["fairmint one", "premium plan", "subscription"],
    entryPoints: ["studio/src/components/Dialogs/UpgradeDialog"],
  },
  {
    filePath: "founders/1.3-early-stage-can-i-use-fairmint.md",
    title: "Early Stage — Can I Use Fairmint?",
    section: "1. Getting Started & Overview",
    number: "1.3",
    audience: "Founders",
    gate: "None",
    collection: "Getting Started",
    searchTerms: ["early stage", "pre-seed", "seed", "startup"],
  },
  {
    filePath: "founders/1.4-later-stages-can-i-use-fairmint.md",
    title: "Later Stages — Can I Use Fairmint?",
    section: "1. Getting Started & Overview",
    number: "1.4",
    audience: "Founders",
    gate: "None",
    collection: "Getting Started",
    searchTerms: ["series A", "series B", "growth stage", "later stage"],
  },
  {
    filePath: "founders/1.5-onboarding-and-setting-up-your-portal.md",
    title: "Onboarding & Setting Up Your Portal",
    section: "1. Getting Started & Overview",
    number: "1.5",
    audience: "Founders",
    gate: "Only shown when the portal is brand new or the user hasn't entered their name yet",
    collection: "Getting Started",
    searchTerms: ["onboarding", "signup", "portal setup", "first login"],
    entryPoints: [
      "studio/src/pages/Onboarding/Signup/index.js",
      "studio/src/layout/portal.js",
    ],
  },
  {
    filePath: "founders/1.6-dashboard-overview.md",
    title: "Dashboard Overview",
    section: "1. Getting Started & Overview",
    number: "1.6",
    audience: "Founders",
    gate: "Visible to Owners and Admins only.",
    collection: "Getting Started",
    searchTerms: ["dashboard", "home page", "overview", "stats"],
    entryPoints: [
      "studio/src/pages/Dashboard/index.js",
      "studio/src/layout/portal.js",
    ],
  },
  {
    filePath: "founders/1.7-is-fairmint-a-broker-dealer.md",
    title: "Is Fairmint a Broker Dealer or Registered Entity?",
    section: "1. Getting Started & Overview",
    number: "1.7",
    audience: "Shared",
    gate: "None",
    collection: "Getting Started",
    searchTerms: ["broker dealer", "registered entity", "SEC", "regulation"],
  },
  {
    filePath: "founders/1.8-what-if-i-stop-using-fairmint.md",
    title: "What If I Want to Stop Using Fairmint?",
    section: "1. Getting Started & Overview",
    number: "1.8",
    audience: "Shared",
    gate: "None",
    collection: "Getting Started",
    searchTerms: ["stop using", "cancel", "offboarding", "leave fairmint"],
  },
  {
    filePath: "founders/1.9-smart-contract-compromised.md",
    title: "What If the Smart Contract or Digital Assets Are Compromised?",
    section: "1. Getting Started & Overview",
    number: "1.9",
    audience: "Shared",
    gate: "None",
    collection: "Getting Started",
    searchTerms: ["smart contract", "compromised", "security", "digital assets"],
  },
];

/* ─── Section 2: Series & Fundraising ──────────────────────────────── */

const S2_FUNDRAISING: ArticleTopic[] = [
  {
    filePath: "founders/2.0-fundraising-with-fairmint.md",
    title: "Fundraising with Fairmint (Overview)",
    section: "2. Series & Fundraising",
    number: "2.0",
    audience: "Founders",
    gate: "None",
    collection: "Fundraising",
    searchTerms: ["fundraising overview", "raise capital", "series"],
    entryPoints: ["studio/src/pages/Series/index.js"],
  },
  {
    filePath: "founders/2.1-create-fundraise-rollup.md",
    title: "Create a Fundraise (Roll Up)",
    section: "2. Series & Fundraising",
    number: "2.1",
    audience: "Founders",
    gate: "Free plan shows upgrade dialog when clicking Raise capital. Requires Fairmint One.",
    collection: "Fundraising",
    searchTerms: ["roll up", "create fundraise", "consolidate investors"],
    entryPoints: [
      "studio/src/components/Dialogs/SeriesTypeDialog/index.js",
      "studio/src/pages/Series/CreateSeries",
    ],
  },
  {
    filePath: "founders/2.2-create-fundraise-safe.md",
    title: "Create a Fundraise (SAFE)",
    section: "2. Series & Fundraising",
    number: "2.2",
    audience: "Founders",
    gate: "Free plan shows upgrade dialog when clicking Raise capital.",
    collection: "Fundraising",
    searchTerms: ["SAFE", "simple agreement", "create fundraise"],
    entryPoints: [
      "studio/src/components/Dialogs/SeriesTypeDialog/index.js",
      "studio/src/pages/Series/CreateSeries",
    ],
  },
  {
    filePath: "founders/2.3-publish-fundraise.md",
    title: "How to Publish a Fundraise",
    section: "2. Series & Fundraising",
    number: "2.3",
    audience: "Founders",
    gate: "Series must be in setup or ready status. Publish button hidden when live or closed.",
    collection: "Fundraising",
    searchTerms: ["publish", "go live", "deal page", "launch fundraise"],
    entryPoints: [
      "studio/src/pages/Series/DealPageEditor",
      "studio/src/components/Dialogs/PublishDialog",
    ],
  },
  {
    filePath: "founders/2.5-how-to-pause-resume-a-fundraise.md",
    title: "How to Pause/Resume a Fundraise",
    section: "2. Series & Fundraising",
    number: "2.5",
    audience: "Founders",
    gate: "Series must be live (to pause) or paused (to resume).",
    collection: "Fundraising",
    searchTerms: ["pause fundraise", "resume fundraise", "suspend"],
  },
  {
    filePath: "founders/2.6-how-to-end-a-fundraise.md",
    title: "How to End a Fundraise",
    section: "2. Series & Fundraising",
    number: "2.6",
    audience: "Founders",
    gate: "Series must be live or paused.",
    collection: "Fundraising",
    searchTerms: ["end fundraise", "close round", "stop fundraising"],
  },
  {
    filePath: "founders/2.7-what-is-a-roll-up-investment.md",
    title: "What is a Roll Up Investment?",
    section: "2. Series & Fundraising",
    number: "2.7",
    audience: "Founders",
    gate: "None",
    collection: "Fundraising",
    searchTerms: ["roll up investment", "consolidated", "single line"],
  },
  {
    filePath: "founders/2.8-what-is-a-ticker-symbol.md",
    title: "What is a Ticker Symbol?",
    section: "2. Series & Fundraising",
    number: "2.8",
    audience: "Founders",
    gate: "None",
    collection: "Fundraising",
    searchTerms: ["ticker symbol", "series symbol", "abbreviation"],
  },
  {
    filePath: "founders/2.9-what-fundraising-templates-are-available.md",
    title: "What Fundraising Templates are Available?",
    section: "2. Series & Fundraising",
    number: "2.9",
    audience: "Founders",
    gate: "None",
    collection: "Fundraising",
    searchTerms: ["templates", "fundraising templates", "SAFE templates"],
  },
  {
    filePath: "founders/2.10-deal-page-design.md",
    title: "Deal Page Design",
    section: "2. Series & Fundraising",
    number: "2.10",
    audience: "Founders",
    gate: "Series must exist. Deal page editor accessible when series is not closed.",
    collection: "Fundraising",
    searchTerms: ["deal page", "editor", "design", "branding", "customize"],
    entryPoints: ["studio/src/pages/Series/DealPageEditor"],
  },
  {
    filePath: "founders/2.11-manage-series-settings.md",
    title: "Manage Your Series",
    section: "2. Series & Fundraising",
    number: "2.11",
    audience: "Founders",
    gate: "Series must exist (not imported). Tabs and actions vary by series status.",
    collection: "Fundraising",
    searchTerms: ["series settings", "manage series", "edit terms"],
    entryPoints: ["studio/src/pages/Series/SeriesDetail"],
  },
  {
    filePath: "founders/2.12-fundraising-for-us-based-c-corps.md",
    title: "Fundraising for US Based C-Corps",
    section: "2. Series & Fundraising",
    number: "2.12",
    audience: "Founders",
    gate: "None",
    collection: "Fundraising",
    searchTerms: ["C-Corp", "Delaware", "US company", "fundraising"],
  },
  {
    filePath: "founders/2.13-fundraising-for-llcs-and-non-us-companies.md",
    title: "Fundraising for LLCs & Non-US Companies",
    section: "2. Series & Fundraising",
    number: "2.13",
    audience: "Founders",
    gate: "None",
    collection: "Fundraising",
    searchTerms: ["LLC", "non-US", "international", "foreign company"],
  },
  {
    filePath: "founders/2.15-soliciting-advertising-506b-vs-506c.md",
    title: "Soliciting & Advertising — 506(b) vs 506(c)",
    section: "2. Series & Fundraising",
    number: "2.15",
    audience: "Shared",
    gate: "None",
    collection: "Fundraising",
    searchTerms: ["506b", "506c", "solicitation", "advertising", "general solicitation"],
  },
  {
    filePath: "founders/2.16-use-your-own-legal-agreement.md",
    title: "Use Your Own Legal Agreement",
    section: "2. Series & Fundraising",
    number: "2.16",
    audience: "Shared",
    gate: "None",
    collection: "Fundraising",
    searchTerms: ["custom agreement", "legal agreement", "own template"],
  },
];

/* ─── Section 3: Cap Table ─────────────────────────────────────────── */

const S3_CAP_TABLE: ArticleTopic[] = [
  {
    filePath: "founders/3.1-upload-import-cap-table.md",
    title: "Import Your Cap Table",
    section: "3. Cap Table",
    number: "3.1",
    audience: "Founders",
    gate: "Super-admins see a direct link to Timeline View; other users see an import dialog",
    collection: "Cap Table",
    searchTerms: ["import", "upload", "cap table", "CSV", "spreadsheet"],
    entryPoints: [
      "studio/src/pages/CapTable/CapTableImport",
      "studio/src/pages/CapTable/CapTableOnboarding",
    ],
  },
  {
    filePath: "founders/3.2-can-i-import-old-investors-into-fairmint.md",
    title: "Can I Import Old Investors into Fairmint?",
    section: "3. Cap Table",
    number: "3.2",
    audience: "Founders",
    gate: "None (FAQ)",
    collection: "Cap Table",
    searchTerms: ["import investors", "old investors", "existing investors"],
  },
  {
    filePath: "founders/3.3-can-i-manage-my-entire-cap-table-with-fairmint.md",
    title: "Can I Manage My Entire Cap Table with Fairmint?",
    section: "3. Cap Table",
    number: "3.3",
    audience: "Founders",
    gate: "None (FAQ)",
    collection: "Cap Table",
    searchTerms: ["manage cap table", "full cap table", "all equity"],
  },
  {
    filePath: "founders/3.4-cap-table-summary-view.md",
    title: "Cap Table Summary View",
    section: "3. Cap Table",
    number: "3.4",
    audience: "Founders",
    gate: "Only visible after cap table has been set up. Export, As-Of, and Pro-Forma disabled until cap table has data.",
    collection: "Cap Table",
    searchTerms: ["summary view", "cap table summary", "capitalization", "ownership"],
    entryPoints: ["studio/src/pages/CapTable/SummaryView"],
  },
  {
    filePath: "founders/3.5-cap-table-holder-view.md",
    title: "Cap Table Holder View",
    section: "3. Cap Table",
    number: "3.5",
    audience: "Founders",
    gate: "Same as Summary View — only visible after cap table has been set up",
    collection: "Cap Table",
    searchTerms: ["holder view", "stakeholder view", "who owns what"],
    entryPoints: ["studio/src/pages/CapTable/HolderView"],
  },
  {
    filePath: "founders/3.6-cap-table-timeline-view.md",
    title: "Cap Table Timeline View",
    section: "3. Cap Table",
    number: "3.6",
    audience: "Founders",
    gate: "Super-admin only (nav item only rendered when superAdmin is true)",
    collection: "Cap Table",
    searchTerms: ["timeline", "history", "cap table changes"],
    entryPoints: ["studio/src/pages/CapTable/TimelineView"],
  },
  {
    filePath: "founders/3.7-pro-forma-cap-table.md",
    title: "Pro-Forma Cap Table",
    section: "3. Cap Table",
    number: "3.7",
    audience: "Founders",
    gate: "Only available after cap table has been set up. Cannot be used while viewing a historical As-Of date.",
    collection: "Cap Table",
    searchTerms: ["pro forma", "what-if", "scenario", "dilution"],
    entryPoints: ["studio/src/pages/CapTable/SummaryView"],
  },
];

/* ─── Section 4: Equity Instruments ────────────────────────────────── */

const S4_INSTRUMENTS: ArticleTopic[] = [
  {
    filePath: "founders/4.1-understanding-shares.md",
    title: "Understanding Shares",
    section: "4. Equity Instruments",
    number: "4.1",
    audience: "Founders",
    gate: "Nav disabled when no Shares series exists. Shows 'Import cap table' fallback link.",
    collection: "Equity Instruments",
    searchTerms: ["shares", "common stock", "preferred stock", "equity"],
    entryPoints: ["studio/src/pages/Shares"],
  },
  {
    filePath: "founders/4.2-understanding-safes.md",
    title: "Understanding SAFEs",
    section: "4. Equity Instruments",
    number: "4.2",
    audience: "Founders",
    gate: "Nav disabled when no fundraising series exists",
    collection: "Equity Instruments",
    searchTerms: ["SAFE", "simple agreement", "future equity", "convertible"],
    entryPoints: ["studio/src/pages/Series"],
  },
  {
    filePath: "founders/4.3-understanding-warrants.md",
    title: "Understanding Warrants",
    section: "4. Equity Instruments",
    number: "4.3",
    audience: "Founders",
    gate: "Nav disabled when no Warrant series exists",
    collection: "Equity Instruments",
    searchTerms: ["warrants", "warrant", "exercise", "strike price"],
    entryPoints: ["studio/src/pages/Shares"],
  },
];

/* ─── Section 5: Grants (ESOP / Equity Grants) ────────────────────── */

const S5_GRANTS: ArticleTopic[] = [
  {
    filePath: "founders/5.1-set-up-an-equity-grant.md",
    title: "Set Up an Equity Grant",
    section: "5. Grants (ESOP / Equity Grants)",
    number: "5.1",
    audience: "Founders",
    gate: "Nav disabled when no Grant series exists",
    collection: "Grants",
    searchTerms: ["equity grant", "ESOP", "stock options", "employee equity"],
    entryPoints: [
      "studio/src/pages/Grants/EquityGrants",
      "studio/src/pages/Grants/CreateGrant",
    ],
  },
  {
    filePath: "founders/5.2-manage-equity-grants.md",
    title: "Manage Equity Grants",
    section: "5. Grants (ESOP / Equity Grants)",
    number: "5.2",
    audience: "Founders",
    gate: "At least one grant series must exist",
    collection: "Grants",
    searchTerms: ["manage grants", "grant list", "vesting", "equity plan"],
    entryPoints: ["studio/src/pages/Grants/EquityGrants"],
  },
  {
    filePath: "founders/5.3-understanding-vesting-schedules.md",
    title: "Understanding Vesting Schedules",
    section: "5. Grants (ESOP / Equity Grants)",
    number: "5.3",
    audience: "Founders",
    gate: "None (concept article)",
    collection: "Grants",
    searchTerms: ["vesting", "cliff", "schedule", "monthly vesting"],
  },
];

/* ─── Section 6: Stakeholders, Investors & Investments ─────────────── */

const S6_STAKEHOLDERS: ArticleTopic[] = [
  {
    filePath: "founders/6.1-view-manage-stakeholders.md",
    title: "View and Manage Stakeholders",
    section: "6. Stakeholders, Investors & Investments",
    number: "6.1",
    audience: "Founders",
    gate: "Always visible",
    collection: "Stakeholders & Investments",
    searchTerms: ["stakeholders", "investors", "manage investors", "investor list"],
    entryPoints: ["studio/src/pages/Stakeholders"],
  },
  {
    filePath: "founders/6.2-deal-invitation-links.md",
    title: "Invite an Investor (Deal Invitation Links)",
    section: "6. Stakeholders, Investors & Investments",
    number: "6.2",
    audience: "Founders",
    gate: "Series must be live",
    collection: "Stakeholders & Investments",
    searchTerms: ["invitation link", "invite investor", "share link", "deal link"],
    entryPoints: [
      "studio/src/pages/CapTable/SeriesDetail/ShareSeriesCard",
      "studio/src/components/Dialogs/EditInvitationLinkDialog.js",
    ],
  },
  {
    filePath: "founders/6.3-how-to-block-an-investor.md",
    title: "How to Block an Investor",
    section: "6. Stakeholders, Investors & Investments",
    number: "6.3",
    audience: "Founders",
    gate: "Investor must exist",
    collection: "Stakeholders & Investments",
    searchTerms: ["block investor", "deny access", "remove investor"],
  },
  {
    filePath: "founders/6.4-how-to-reset-an-investor-country.md",
    title: "How to Reset an Investor Country",
    section: "6. Stakeholders, Investors & Investments",
    number: "6.4",
    audience: "Founders",
    gate: "Investor must exist",
    collection: "Stakeholders & Investments",
    searchTerms: ["reset country", "investor country", "change country"],
  },
  {
    filePath: "founders/6.5-can-organizations-limit-investor-type-and-number.md",
    title: "Can Organizations Limit Investor Type and Number?",
    section: "6. Stakeholders, Investors & Investments",
    number: "6.5",
    audience: "Shared",
    gate: "None (FAQ)",
    collection: "Stakeholders & Investments",
    searchTerms: ["investor limits", "accredited", "investor type", "99 investors"],
  },
  {
    filePath: "founders/6.6-view-manage-investments.md",
    title: "View and Manage Investments",
    section: "6. Stakeholders, Investors & Investments",
    number: "6.6",
    audience: "Founders",
    gate: "Always visible",
    collection: "Stakeholders & Investments",
    searchTerms: ["investments", "investment list", "manage investments"],
    entryPoints: ["studio/src/pages/Investments"],
  },
];

/* ─── Section 7: Tax & Compliance ──────────────────────────────────── */

const S7_TAX_COMPLIANCE: ArticleTopic[] = [
  {
    filePath: "founders/7.1-filings-sec-form-d.md",
    title: "Filings (SEC Form D)",
    section: "7. Tax & Compliance",
    number: "7.1",
    audience: "Founders",
    gate: "Always visible",
    collection: "Compliance",
    searchTerms: ["form D", "SEC filing", "filings", "Regulation D"],
    entryPoints: ["studio/src/pages/Filings"],
  },
  {
    filePath: "founders/7.2-risk-factors.md",
    title: "Risk Factors",
    section: "7. Tax & Compliance",
    number: "7.2",
    audience: "Founders",
    gate: "Always visible",
    collection: "Compliance",
    searchTerms: ["risk factors", "disclosures", "investor risk"],
    entryPoints: ["studio/src/pages/RiskFactors"],
  },
  {
    filePath: "founders/7.3-state-fees-blue-sky.md",
    title: "State Fees (Blue Sky)",
    section: "7. Tax & Compliance",
    number: "7.3",
    audience: "Founders",
    gate: "Always visible",
    collection: "Compliance",
    searchTerms: ["blue sky", "state fees", "state filing", "notice filing"],
    entryPoints: ["studio/src/pages/StateFees"],
  },
  {
    filePath: "founders/7.4-409a-report.md",
    title: "409A Report",
    section: "7. Tax & Compliance",
    number: "7.4",
    audience: "Founders",
    gate: "Always visible",
    collection: "Compliance",
    searchTerms: ["409A", "valuation", "fair market value"],
    entryPoints: ["studio/src/pages/Report409A"],
  },
  {
    filePath: "founders/7.5-jurisdictions.md",
    title: "Jurisdictions",
    section: "7. Tax & Compliance",
    number: "7.5",
    audience: "Founders",
    gate: "Always visible",
    collection: "Compliance",
    searchTerms: ["jurisdictions", "states", "countries", "where investors"],
    entryPoints: ["studio/src/pages/Jurisdictions"],
  },
];

/* ─── Section 8: Documents ─────────────────────────────────────────── */

const S8_DOCUMENTS: ArticleTopic[] = [
  {
    filePath: "founders/8.1-documents-overview.md",
    title: "Documents Overview",
    section: "8. Documents",
    number: "8.1",
    audience: "Founders",
    gate: "Always visible",
    collection: "Documents",
    searchTerms: ["documents", "agreements", "contracts", "legal documents"],
    entryPoints: ["studio/src/pages/Documents"],
  },
  {
    filePath: "founders/8.2-generate-shareholder-register-pdf.md",
    title: "Generate a Shareholder Register PDF",
    section: "8. Documents",
    number: "8.2",
    audience: "Founders",
    gate: "Only available after cap table has been set up",
    collection: "Documents",
    searchTerms: ["shareholder register", "PDF", "generate report", "stock ledger"],
    entryPoints: ["studio/src/pages/CapTable/SummaryView"],
  },
];

/* ─── Section 9: Settings ──────────────────────────────────────────── */

const S9_SETTINGS: ArticleTopic[] = [
  {
    filePath: "founders/9.1-general-settings.md",
    title: "General Settings (Company Info, Branding)",
    section: "9. Settings",
    number: "9.1",
    audience: "Founders",
    gate: "Always available. Warning badges until setup tasks cleared.",
    collection: "Settings",
    searchTerms: ["settings", "company info", "branding", "logo", "company name"],
    entryPoints: ["studio/src/pages/Settings/General"],
  },
  {
    filePath: "founders/9.2-bank-details-funding-options.md",
    title: "Bank Details / Funding Options",
    section: "9. Settings",
    number: "9.2",
    audience: "Founders",
    gate: "Always available",
    collection: "Settings",
    searchTerms: ["bank details", "funding options", "wire transfer", "payment"],
    entryPoints: ["studio/src/pages/Settings/BankDetails"],
  },
  {
    filePath: "founders/9.3-team-management.md",
    title: "Team Management",
    section: "9. Settings",
    number: "9.3",
    audience: "Founders",
    gate: "Always available. Actions vary by role.",
    collection: "Settings",
    searchTerms: ["team", "roles", "admin", "invite team", "permissions"],
    entryPoints: ["studio/src/pages/Settings/Team"],
  },
  {
    filePath: "founders/9.4-integrations.md",
    title: "Integrations",
    section: "9. Settings",
    number: "9.4",
    audience: "Founders",
    gate: "Always available. Telegram hidden when bot username unset.",
    collection: "Settings",
    searchTerms: ["integrations", "telegram", "notifications", "webhooks"],
    entryPoints: ["studio/src/pages/Settings/Integrations"],
  },
  {
    filePath: "founders/9.5-custom-domain.md",
    title: "Custom Domain (DNS)",
    section: "9. Settings",
    number: "9.5",
    audience: "Founders",
    gate: "Always available",
    collection: "Settings",
    searchTerms: ["custom domain", "DNS", "CNAME", "branded URL"],
    entryPoints: ["studio/src/pages/Settings/CustomDomain"],
  },
];

/* ─── Section 10: Legal & Compliance (Conceptual / FAQ) ────────────── */

const S10_LEGAL: ArticleTopic[] = [
  {
    filePath: "founders/10.1-kyc-kyb-accreditation-aml.md",
    title: "KYC/KYB, Accreditation, and AML",
    section: "10. Legal & Compliance (Conceptual / FAQ)",
    number: "10.1",
    audience: "Shared",
    gate: "None",
    collection: "Legal & Compliance",
    searchTerms: ["KYC", "KYB", "accreditation", "AML", "identity verification"],
  },
  {
    filePath: "founders/10.2-transfer-restrictions.md",
    title: "How Are Transfer Restrictions Managed?",
    section: "10. Legal & Compliance (Conceptual / FAQ)",
    number: "10.2",
    audience: "Shared",
    gate: "None",
    collection: "Legal & Compliance",
    searchTerms: ["transfer restrictions", "share transfer", "lockup"],
  },
  {
    filePath: "founders/10.3-securities-exemptions.md",
    title: "Which Securities Exemptions is Fairmint Compatible With?",
    section: "10. Legal & Compliance (Conceptual / FAQ)",
    number: "10.3",
    audience: "Shared",
    gate: "None",
    collection: "Legal & Compliance",
    searchTerms: ["securities exemptions", "Reg D", "Reg CF", "Reg A"],
  },
];

/* ─── Export ───────────────────────────────────────────────────────── */

export const FOUNDER_TOPICS: ArticleTopic[] = [
  ...S1_GETTING_STARTED,
  ...S2_FUNDRAISING,
  ...S3_CAP_TABLE,
  ...S4_INSTRUMENTS,
  ...S5_GRANTS,
  ...S6_STAKEHOLDERS,
  ...S7_TAX_COMPLIANCE,
  ...S8_DOCUMENTS,
  ...S9_SETTINGS,
  ...S10_LEGAL,
];
